/**
 * Pure game logic — no DOM / window / wx.
 */

export type { ChopOutcome } from './chop-types.ts';
export type { Axe, Species } from './types.ts';
export {
  resolveChop,
  getSweetSliderRange,
  axeForceScale,
  sweetHalfWindow,
  type ResolveChopInput,
} from './resolve-chop.ts';

export type { FractureHook, FractureHookContext } from './hooks.ts';

export {
  planFracture,
  cleaveNormalXZ,
  cleaveNormalFromCameraFacing,
  rotateCleaveNormal90,
  advanceOrientChopCount,
  CHOPS_BEFORE_ORIENT_ROTATE,
  isRechopWorthy,
  isFirewoodChip,
  isFirewoodByVolumeAspect,
  volumeInchesFromBBox,
  horizontalAspectXZ,
  horizontalAspectFromSize,
  thicknessInchesAlong,
  isTooThinToSplit,
  decideTooThinChop,
  shouldTossOnTooThin,
  azimuthNudgeVelocity,
  lateralOffsetFromDiameter,
  INCH,
  FIREWOOD_VOL_ABS_MIN,
  FIREWOOD_VOL_MAX,
  FIREWOOD_ASPECT_RESCUE,
  VOLUME_BBOX_FILL,
  MIN_SPLIT_THICKNESS_IN,
  AZIMUTH_NUDGE_DAMP,
  FACE_GAP_DIAMETER_FRAC,
  BOUNCE_POP_HEIGHT,
  BOUNCE_DURATION_MS,
  BOUNCE_YAW_JITTER_DEG,
  BOUNCE_TILT_DEG,
  TIP_DROP_DURATION_MS,
  TIP_DROP_DURATION_JIT_MS,
  TIP_DROP_ANGLE_DEG,
  TIP_DROP_ANGLE_JIT_DEG,
  TIP_DROP_YAW_JIT_DEG,
  TIP_DROP_ARC_HEIGHT,
  TIP_DROP_REST_RADIAL,
  TIP_DROP_REST_RADIAL_JIT,
  TIP_DROP_SCATTER_RADIAL,
  TIP_DROP_SCATTER_RADIAL_JIT,
  TIP_DROP_GROUND_PAD,
  TIP_DROP_POST_SETTLE_MS,
  YARD_GROUND_Y,
  GROUND_SETTLE_EPS,
  RING_PILE_RADIUS,
  RING_PILE_START_ANGLE,
  RING_PILE_ARC_SPAN,
  RING_PILE_TIER_DEPTH,
  RING_PILE_SLOT_WIDTH,
  RING_PILE_RADIAL_JIT,
  RING_PILE_MAX_PER_TIER,
  RING_PILE_GROUND_PAD,
  RING_PILE_ROLL_JIT,
  RING_PILE_RECYCLE_MS,
  RING_PILE_RECYCLE_JIT_MS,
  RING_PILE_STAGGER_MS,
  planRingPileSlots,
  ringPileSimToWorldAxes,
  pickLocalGrainAxis,
  isCrossSectionXThinner,
  basisDeterminant,
  MAX_RECHOP_GENERATION,
  MIN_RECHOP_DIAGONAL,
  MAX_LIVE_FRAGMENTS,
  TINY_CHIP_DIAGONAL,
  easeSmoothstep,
  normalizePushXZ,
  tipDropRestPose,
  sampleTipDropPose,
  settlePositionY,
  type FracturePlan,
  type FracturePlanInput,
  type FractureAxeStats,
  type SplitStyle,
  type TooThinChopDecision,
  type RingPileSlot,
} from './fracture-plan.ts';
